# name: mocki
# port: 4000
# endpoints:
#   - path: /graphql
#     method: get
#     responses:
#       - statusCode: 200
#         body:
#           data:
#             todos:
#               - id: !Fake uuid
#                 description: !Fake sentence
#               - id: !Fake uuid
#                 description: !Fake sentence
#               - id: !Fake uuid
#                 description: !Fake sentence
#                 completed: false
#               - id: !Fake uuid
#                 description: !Fake sentence
#               - id: !Fake uuid
#                 description: !Fake sentence
name: mocki
port: 4000
endpoints:
  - path: /graphql
    method: post
    graphql:
      mocks:
        Todo:
          id: !Fake uuid
          description: !Fake sentence
          completed: false
      schema: |
        type Todo {
          id: ID!
          description: String!
          completed: Boolean!
        }

        type Query {
          todos: [Todo!]!
        }

        type Mutation {
          updateTodo(id: ID!, completed: Boolean!): Todo!
        }
